name: 'go_message_processor'
version: '1'

services:

  httphandler1:
    image: go_message_processor-httphandler1
    build: ./services/httphandler/
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_CREDENTIALS=postgres://postgres:M8&wer1GHcbT77zV@db-httphandler:5432/messages?sslmode=disable
      - BOOTSTRAP_SERVERS=kafka-broker-1:19092
      - KAFKA_PRODUCER_SETTINGS=nil
    depends_on:
      - db-httphandler
      - kafka-controller-1

  httphandler2:
    image: go_message_processor-httphandler1
    ports:
      - "9080:8080"
    environment:
      - PORT=8080
      - DB_CREDENTIALS=postgres://postgres:M8&wer1GHcbT77zV@db-httphandler:5432/messages?sslmode=disable
      - BOOTSTRAP_SERVERS=kafka-broker-1:19092
      - KAFKA_PRODUCER_SETTINGS=nil
    depends_on:
      - httphandler1

  db-httphandler:
    image: "postgres:12.19"
    restart: always
    #shm_size: 128mb
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: M8&wer1GHcbT77zV
      POSTGRES_USER: postgres
      POSTGRES_DB: messages
    volumes:
      - ./dbstorage/httpHandlerDb/data:/var/lib/postgresql/data
      - ./scripts/httpHandlerPgInit/create_table_messages.sql:/docker-entrypoint-initdb.d/create_table_messages.sql

  messageprocessor1:
    image: go_message_processor-messageprocessor1
    build: ./services/messageprocessor/
    environment:
      - DB_CREDENTIALS=postgres://postgres:M8&wer1GHcbT77zV@db-messageprocessor:5432/processedmessages?sslmode=disable
      - BOOTSTRAP_SERVERS=kafka-broker-1:19092
      - KAFKA_CONSUMER_GROUP=messageprocessors
    depends_on:
      - db-messageprocessor
      - kafka-controller-1

  messageprocessor2:
    image: go_message_processor-messageprocessor1
    environment:
      - DB_CREDENTIALS=postgres://postgres:M8&wer1GHcbT77zV@db-messageprocessor:5432/processedmessages?sslmode=disable
      - BOOTSTRAP_SERVERS=kafka-broker-1:19092
      - KAFKA_CONSUMER_GROUP=messageprocessors
    depends_on:
      - messageprocessor1

  db-messageprocessor:
    image: "postgres:12.19"
    restart: always
    #shm_size: 128mb
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: M8&wer1GHcbT77zV
      POSTGRES_USER: postgres
      POSTGRES_DB: processedmessages
    volumes:
      - ./dbstorage/messageProcessorDb/data:/var/lib/postgresql/data
      - ./scripts/messageProcessorPgInit/create_table_consumedmessages.sql:/docker-entrypoint-initdb.d/create_table_consumedmessages.sql

  messageprocessor_statistics_server:
    image: go_message_processor-messageprocessor_statistics_server
    build: ./services/processingstatsserver/
    ports:
      - "1080:1080"
    environment:
      - PORT=1080    
      - DB_CREDENTIALS=postgres://postgres:M8&wer1GHcbT77zV@db-messageprocessor:5432/processedmessages?sslmode=disable
    depends_on:
      - messageprocessor1

  # creating topics
  kafka-create-topics:
    image: "confluentinc/cp-kafka:7.7.0"
    depends_on:
      - kafka-controller-1
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-controller-1:9092'
      KAFKA_LISTENERS: PLAINTEXT://:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-create-topics:19092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-create-topics:19092
      CONNECT_BOOTSTRAP_SERVERS: kafka-create-topics:19092, kafka-broker-1:19092, kafka-broker-2:19092, kafka-broker-3:19092
    volumes:
      - ./scripts/kafkainit/create_topic_messages.sh:/scripts/create_topic_messages
    command: bash /scripts/create_topic_messages


  kafka-controller-1:
    image: "confluentinc/cp-kafka:7.7.0"
    restart: always
    ports:
      - 19092:9092 
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-controller-1:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'CONTROLLER://:9092'
      # KAFKA_ADVERTISED_LISTENERS: 'CONTROLLER://127.0.0.1:19092' #added, should add listener to brokers and replace advertised listeners
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-controller-1:9092
    volumes:
      - ./config/kafka01/server.properties:/kafka/config/kraft/server.properties
      - ./kafkastorage/controller1:/var/lib/kafka/data


  kafka-broker-1:
    image: "confluentinc/cp-kafka:7.7.0"
    restart: always
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-controller-1:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://:19092, PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://:19092, PLAINTEXT_HOST://localhost:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-broker-1:19092
      CONNECT_BOOTSTRAP_SERVERS: kafka-broker-1:19092, kafka-broker-2:19092, kafka-broker-3:19092
    volumes:
    - ./kafkastorage/broker1:/var/lib/kafka/data
    depends_on:
      - "kafka-controller-1"


  kafka-broker-2:
    image: "confluentinc/cp-kafka:7.7.0"
    restart: always
    ports:
      - 39092:9092
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-controller-1:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://:19092, PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://:19092, PLAINTEXT_HOST://localhost:39092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-broker-2:19092
      CONNECT_BOOTSTRAP_SERVERS: kafka-broker-1:19092, kafka-broker-2:19092, kafka-broker-3:19092

    volumes:
      - ./kafkastorage/broker2:/var/lib/kafka/data
    depends_on:
      - kafka-controller-1

  kafka-broker-3:
    image: "confluentinc/cp-kafka:7.7.0"
    restart: always
    ports:
      - 49092:9092
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-controller-1:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://:19092, PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://:19092, PLAINTEXT_HOST://localhost:49092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-broker-3:19092
      CONNECT_BOOTSTRAP_SERVERS: kafka-broker-1:19092, kafka-broker-2:19092, kafka-broker-3:19092
    volumes:
      - ./kafkastorage/broker3:/var/lib/kafka/data
    depends_on:
      - kafka-controller-1
