FROM golang:1.22.3
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
COPY consumer ./consumer/
COPY store ./store/
RUN CGO_ENABLED=1 GOOS=linux go build -o /messageprocessor
RUN chmod +x /messageprocessor

CMD ["/messageprocessor"]