FROM golang:1.22.3
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
COPY poller ./poller/
COPY server ./server/
COPY store ./store/
RUN CGO_ENABLED=0 GOOS=linux go build -o /processingstatsserver
RUN chmod +x /processingstatsserver

EXPOSE 8080

CMD ["/processingstatsserver"]