FROM golang:1.22.3
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
COPY producer ./producer/
COPY server ./server/
COPY store ./store/
RUN CGO_ENABLED=1 GOOS=linux go build -o /httphandler
RUN chmod +x /httphandler

EXPOSE 8080

CMD ["/httphandler"]